1.21:
  sha256: 7ab464e20932eb024ba6378738da77a4a03642d63b0ca9772b612a7cf27baec1
  root_url: http://cns-online.org/download/v1.21/cns_solve_1.21_all.tar.gz
  url_type: cns_url
  expand: True

#  resources:
#    aria2.3.2.tar.gz:
#      url_type: aria_url
#      url: http://aria.pasteur.fr/archives/aria2.3.2.tar.gz
#      hash: 13a41f8916e895e2edeec1dd0eb84eb632f10b0fef9558e195d8876801daa4fa



