name: Test nmrpack install

on:

  push:
    branches: [ master ]

  workflow_dispatch:




jobs:

  install_nmrpack:
    name: install nmrpack and spack
    runs-on: macos-latest

    uses: github/actions/install_spack.ym

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: setup nmrpack
      run: |
        . install_spack.sh

    - name: test nmrpack
      run: |
        . spack/share/spack/setup-env.sh
        spack repo list | grep nmrpack
