name: Test nmrpack install

on:

  push:
    branches: [ master ]

  workflow_dispatch:


jobs:

  install_nmrpack:
    name: install nmrpack and spack
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: download spack
      run: |
        curl -L https://github.com/spack/spack/releases/download/v0.16.0/spack-0.16.0.tar.gz -o spack.tar.gz

    - name: extract spack
      run: |
        mkdir spack
        tar --strip-components=1  -C spack -zxvf spack.tar.gz

    - name: install spack
      run: |
        cd spack
        echo `pwd`
        . .github/workflows/install_spack.sh
        cd ..

    - name: install nmrpack
      run: |

        echo `pwd`
        echo `ls`
        curl -L https://github.com/varioustoxins/nmrpack/archive/master.zip -o nmrpack-master.zip
        unzip nmrpack-master.zip
        mv nmrpack-master nmrpack
        . spack/share/spack/setup-env.sh
        spack repo add nmrpack

    - name: test nmrpack
      run: |
        . spack/share/spack/setup-env.sh
        spack repo list | grep nmrpack
