# .github/workflows/tests.yml
name: nmrpipe_grabber
on:
#  schedule:
#    - cron: '0-59 * * *'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: 'current-time'
        with:
          format: 'YYYY-MM-DDTHH:mm:ssZ'

      - name: git clone
        run: |
          git clone https://github.com/varioustoxins/nmrpipe-tracker.git

      - name: checkout master
        working-directory: ./nmrpipe-tracker
        run: |
          git checkout master

#      - name: set upstream
#        working-directory: ./nmrpipe-tracker
#        run: |
#          git branch --set-upstream-to=origin/master

      # Runs a set of commands using the runners shell
      - name: date stamp
        run: |
          touch nmrpipe-tracker/DATE-STAMP
          echo ${{ steps.current-time.outputs.formattedTime }} > nmrpipe-tracker/DATE-STAMP

      - name: commit
        uses: EndBug/add-and-commit@v7

        with:
          message: test
          cwd: ./nmrpipe-tracker
          add: DATE-STAMP
          branch: master