name: Test spack install

on:

  push:
    branches: [ main ]

  workflow_dispatch:


jobs:

  build:
    runs-on: macos-latest


    steps:

      - name: download spack
        run: |
          git clone https://github.com/spack/spack spack
          cd spack
          git checkout releases/v0.16

#          git clone -c feature.manyFiles=true https://github.com/spack/spack.git
#          curl -L https://github.com/spack/spack/archive/develop.zip -o ./develop.zip
