name: Test nmrpack install

on:

  push:
    branches: [ master ]

  workflow_dispatch:




jobs:

  install_nmrpack:
    name: install nmrpack and spack
    runs-on: macos-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: checkout nmrpack
      uses: actions/checkout@v2

    - name: setup actions
      run: |
        . .github/workflows/scripts/setup_actions.sh

    - name: setup nmrpack
      run: |
        echo `pwd`
        echo `ls -a`
#        . .github/workflows/scripts/install_nmrpack.sh

#    - name: test nmrpack
#      run: |
#        . spack/share/spack/setup-env.sh
#        spack repo list | grep nmrpack
