name: Test spack install

on:

  push:
    branches: [ master ]

  workflow_dispatch:


jobs:

  install_gcc:
    name: gcc with clang
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: download spack
      run: |
        git clone https://github.com/spack/spack spack

    - name: checkout latest spack
      run: |
        cd spack
        git checkout releases/v0.16

    - name: install spack
      run: |
        cd spack
        echo `pwd`
        . .github/workflows/install_spack.sh
        cd ..
        curl -L https://github.com/varioustoxins/nmrpack/archive/master.zip -o nmrpack-master.zip
        unzip nmrpack-master.zip
        mv nmrpack-master nmrpack
        spack repo add nmrpack
        spack install nmrpipe
        spack test nmrpipe

#    - name: spack install
#      run: |
#        . .github/workflows/install_spack.sh
#        # 9.2.0 is the latest version on which we apply homebrew patch
#        spack install -v --fail-fast py-vermin
#
#    - name: spack install
#      run: |
#        ls spack


#  build:
#    runs-on: ubuntu-latest #macos-latest
#
#
#    steps:
#
#      - name: download spack
#        run: |
#          git clone https://github.com/spack/spack spack
#
#      - name: checkout latest spack
#        run: |
#          cd spack
#          git checkout releases/v0.16
#
#      - name: add spack to path
#        run: |
#         . ./spack/.github/workflows/install_spack.sh



#          git clone -c feature.manyFiles=true https://github.com/spack/spack.git
#          curl -L https://github.com/spack/spack/archive/develop.zip -o ./develop.zip
