name: Test spack install of nmrpipe

on:

#  push:
#    branches: [ master ]

  workflow_dispatch:


jobs:

  install_nmrpipe:
    name: install nmrpipe with spack
    runs-on: macos-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: download spack
      run: |
        git clone https://github.com/spack/spack spack

    - name: checkout latest spack
      run: |
        cd spack
        git checkout releases/v0.16

    - name: install spack
      run: |
        cd spack
        echo `pwd`
        . .github/workflows/install_spack.sh
#        cd ..

    - name: install nmrpack
      run: |
        curl -L https://github.com/varioustoxins/nmrpack/archive/master.zip -o nmrpack-master.zip
        unzip nmrpack-master.zip
        mv nmrpack-master nmrpack
        spack repo add nmrpack

    - name: test nmrpack
      run: |
        spack repo list | grep nmrpack




