name: Test spack install of nmrstarlib

on:

#  push:
#    branches: [ master ]

  workflow_dispatch:


jobs:

  install_nmrstarlib:
    name: install nmrstarlib with spack
    runs-on: macos-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: checkout nmrpack
      uses: actions/checkout@v2

    - name: setup actions
      run: |
        . .github/workflows/scripts/setup_actions.sh

    - name: setup nmrpack
      run: |
        . .github/workflows/scripts/install_nmrpack.sh

    - name: install and test nmrstarlib with python3.6
      run: |
        . spack/share/spack/setup-env.sh
        spack install py-nmstartlib

    - name: install and test nmrstarlib with python2.7
      run: |
        . spack/share/spack/setup-env.sh
        spack install py-nmstartlib^python@:2.7






