
# This is a basic workflow to help you get started with Actions

name: Update NMRPipe

# Controls when the action will run.
on:

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Python packages
        uses: py-actions/py-dependency-install@v2
        with:
          path: .github/workflows/requirements.txt

      - name: setup PYTHONPATH
        run: |
          echo "PYTHONPATH=tools" >> $GITHUB_ENV


      - name: Get nmrpipe package.yml ibbr
        run: |
          python3 tools/checksum_url.py --root https://www.ibbr.umd.edu/nmrpipe/install.html --template --navigator nmrpipe  --output  nmrpack  --main install.com *.com > nmrpipe_ibbr_package.yml
          echo ibbr
          cat nmrpipe_ibbr_package.yml


      - name: Get nmrpipe package.yml github
        run: |
          python3 tools/checksum_url.py --root https://github.com/varioustoxins/nmrpipe-tracker --template --navigator github_release  --output nmrpack  --main install.com *.com  > nmrpipe_github_package.yml
          echo github
          cat nmrpipe_github_package.yml

      - name: merge package files
        run: |
          python3 tools/combine_packages.py --prefer ibbr nmrpipe_ibbr_package.yml nmrpipe_github_package.yml > nmrpipe_package.yml
          cat nmrpipe_package.yml