
# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the action will run.
on:

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Python packages
        uses: py-actions/py-dependency-install@v2
        with:
          path: .github/workflows/requirements.txt

      # Runs a set of commands using the runners shell
      - name: Update nmrpipe
        run: |
          python3 tools/checksum_url.py --root https://www.ibbr.umd.edu/nmrpipe/install.html --template --navigator nmrpipe  *.com