
# This is a basic workflow to help you get started with Actions

name: Update NMRPipe

# Controls when the action will run.
on:

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install Python packages
        uses: py-actions/py-dependency-install@v2
        with:
          path: .github/workflows/requirements.txt

      - name: setup PYTHONPATH
        run: |
          echo "PYTHONPATH=tools" >> $GITHUB_ENV

      - name: Get nmrpipe package.yml ibbr
        run: |
          python3 tools/checksum_url.py --root https://www.ibbr.umd.edu/nmrpipe/install.html --template --navigator nmrpipe  --output  nmrpack *.com *.tZ > nmrpipe_ibbr_package.yaml

      - name: Get nmrpipe package.yml github
        run: |
          python3 tools/checksum_url.py --root https://github.com/varioustoxins/nmrpipe-tracker --template --navigator github_release  --output nmrpack  --main NMRPipeX.tZ *.com *.tZ   > nmrpipe_github_package.yaml

      - name: merge package files
        run: |
          python3 tools/combine_packages.py --prefer ibbr nmrpipe_ibbr_package.yaml nmrpipe_github_package.yaml > nmrpipe_package.yaml

      - name: cleanup_package_file
        run: |
          python3 tools/post_process_nmrpipe.py  nmrpipe_package.yaml > packages/nmrpipe/package.yaml

      - name: cleanup files
        run: |
          rm nmrpipe_package.yaml
          rm nmrpipe_ibbr_package.yaml
          rm nmrpipe_github_package.yaml

      - name: Get current time
        uses: srfrnk/current-time@master
        id: 'current-time'
        with:
          format: 'YYYY-MM-DDTHH:mm:ssZ'

      - name: Commit
        uses: EndBug/add-and-commit@v7

        with:
          message: updated nmrpipe on ${{ steps.current-time.outputs.formattedTime }}
          branch: master
          add: packages/nmrpipe/package.yaml

